[2024-11-05T22:14:09.720+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-11-05T22:14:07.921907+00:00 [queued]>
[2024-11-05T22:14:09.728+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-11-05T22:14:07.921907+00:00 [queued]>
[2024-11-05T22:14:09.730+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-05T22:14:09.738+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-11-05 22:14:07.921907+00:00
[2024-11-05T22:14:09.745+0000] {standard_task_runner.py:57} INFO - Started process 85 to run task
[2024-11-05T22:14:09.748+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-11-05T22:14:07.921907+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmppjzakuw2']
[2024-11-05T22:14:09.753+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask reddit_extraction
[2024-11-05T22:14:09.793+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-11-05T22:14:07.921907+00:00 [running]> on host 670f27e5f990
[2024-11-05T22:14:09.846+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bruno Xie' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T22:14:07.921907+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T22:14:07.921907+00:00'
[2024-11-05T22:14:09.849+0000] {logging_mixin.py:151} WARNING - Version 7.7.1 of praw is outdated. Version 7.8.1 was released Friday October 25, 2024.
[2024-11-05T22:14:09.852+0000] {logging_mixin.py:151} INFO - connected to Reddit!
[2024-11-05T22:14:10.778+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3790, in get_loc
    return self._engine.get_loc(casted_key)
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'selftext'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 12, in reddit_pipeline
    post_df = transform_data(post_df)
  File "/opt/airflow/etls/reddit_etl.py", line 42, in transform_data
    post_df['selftext'] = post_df['selftext'].astype(str)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 3896, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3797, in get_loc
    raise KeyError(key) from err
KeyError: 'selftext'
[2024-11-05T22:14:10.795+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, execution_date=20241105T221407, start_date=20241105T221409, end_date=20241105T221410
[2024-11-05T22:14:10.806+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 10 for task reddit_extraction ('selftext'; 85)
[2024-11-05T22:14:10.819+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-05T22:14:10.833+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
