[2024-11-05T22:59:49.126+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-11-05T22:59:44.635351+00:00 [queued]>
[2024-11-05T22:59:49.133+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-11-05T22:59:44.635351+00:00 [queued]>
[2024-11-05T22:59:49.134+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-05T22:59:49.142+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): s3_upload> on 2024-11-05 22:59:44.635351+00:00
[2024-11-05T22:59:49.146+0000] {standard_task_runner.py:57} INFO - Started process 100 to run task
[2024-11-05T22:59:49.150+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 's3_upload', 'manual__2024-11-05T22:59:44.635351+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpbwuyii4s']
[2024-11-05T22:59:49.153+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask s3_upload
[2024-11-05T22:59:49.187+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_reddit_pipeline.s3_upload manual__2024-11-05T22:59:44.635351+00:00 [running]> on host 670f27e5f990
[2024-11-05T22:59:49.231+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bruno Xie' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='s3_upload' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T22:59:44.635351+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T22:59:44.635351+00:00'
[2024-11-05T22:59:49.841+0000] {logging_mixin.py:151} INFO - Bucket already exists
[2024-11-05T22:59:49.842+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/aws_s3_pipeline.py", line 9, in upload_s3_pipeline
    upload_to_s3(s3, file_path, AWS_BUCKET_NAME, file_path.split('/')[-1])
  File "/opt/airflow/etls/aws_etl.py", line 25, in upload_to_s3
    s3.put(file_path, bucket='/raw/'+s3_file_name)
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 85, in sync
    coro = func(*args, **kwargs)
TypeError: _put() missing 1 required positional argument: 'rpath'
[2024-11-05T22:59:49.853+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=s3_upload, execution_date=20241105T225944, start_date=20241105T225949, end_date=20241105T225949
[2024-11-05T22:59:49.863+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task s3_upload (_put() missing 1 required positional argument: 'rpath'; 100)
[2024-11-05T22:59:49.893+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-05T22:59:49.906+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
